apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforma-monitorizare
  namespace: monitoring
  labels:
    app: platforma-monitorizare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platforma-monitorizare
  template:
    metadata:
      labels:
        app: platforma-monitorizare
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-logs-config
            items:
              - key: default.conf
                path: default.conf
      containers:
        - name: monitoring
          image: mateimonicamihaela/monitoring:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: INTERVAL
              value: "5"
            - name: OUT_FILE
              value: "/data/system-state.log"
          volumeMounts:
            - name: shared-data
              mountPath: /data
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

        - name: backup
          image: mateimonicamihaela/backup:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKUP_INTERVAL
              value: "5"
            - name: SRC_FILE
              value: "/data/system-state.log"
            - name: BACKUP_DIR
              value: "/data/backup"
            - name: MAX_BACKUPS
              value: "10"
          volumeMounts:
            - name: shared-data
              mountPath: /data
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

        - name: nginx
          image: nginx:1.27-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html/logs
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: platforma-monitorizare
  namespace: monitoring
  labels:
    app: platforma-monitorizare
spec:
  type: NodePort
  selector:
    app: platforma-monitorizare
  ports:
    - name: http
      port: 80
      targetPort: 80
