services:
  monitoring:
    image: mateimonicamihaela/monitoring:latest
    container_name: monitoring-service
    environment:
      - INTERVAL=${INTERVAL:-5}
      - OUT_FILE=${OUT_FILE:-/data/system-state.log}
    volumes:
      - ../data:/data
    restart: unless-stopped

  backup:
    image: mateimonicamihaela/backup:latest
    container_name: backup-service
    environment:
      - BACKUP_INTERVAL=${BACKUP_INTERVAL:-5}
      - SRC_FILE=${SRC_FILE:-/data/system-state.log}
      - BACKUP_DIR=${BACKUP_DIR:-/data/backup}
      - MAX_BACKUPS=${MAX_BACKUPS:-10}
    depends_on:
      - monitoring
    volumes:
      - ../data:/data
    restart: unless-stopped
